services:
  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=bn_keycloak
      - KC_DB_URL_DATABASE=bitnami_keycloak
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=8080
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_PORT=5432
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile

  postgresql:
    image: docker.io/bitnami/postgresql:16.0.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    ports:
      - "5455:5432"